
jobs:
  docker_build:
    steps:
      - name: Build Docker image
        type: docker
        build:
          dockerfile: Dockerfile
          tag: my-app:latest
        push: true
    depends_on:
      - test
