name: My Pipeline

jobs:
  build:
    steps:
      - name: Build application
        image: node:18-alpine
        commands:
          - npm install
          - npm run build

  # test:
  #   steps:
  #     - name: Run tests
  #       image: node:18-alpine
  #       commands:
  #         - npm test
  #   depends_on:
  #     - build

  docker_build:
    steps:
      - name: Build Docker image
        image: node:18-alpine
        commands:
          - docker build -t nextjsgit:v1 .
  deploy:
    steps:
    - name: Deploy to Docker Hub
      commands:
        - docker run -d -p 3000:3000 nextjsgit:v1
    #     build:
    #       dockerfile: Dockerfile
    #       tag: my-app:latest
    #     push: true
    # depends_on:
    #   - test
